### ISSUE TITLE
A try for 《机电一体化课程》

### ISSUE THREAD

**Issue by DragonFaty** [EightEggs/CuBiC#2]
I want to do a course design for a Mechatronics Course, how much will this project cost to implement? Another issue is that I am the only one to undertake this project, will it be  easy for a freshman to implement?

**Comment by EightEggs** [comment]
Hi @DragonFaty, glad that you are interested in our project. 

The cost of implementing this project mainly depending on the purchase of hardware, such as the microcontroller, stepper motor and camera. You can contact online sellers for the specific price. As for me, I used Raspberry Pi 4 as the microcontroller just because I was more familiar with `Python` than `C`. However, I believe using a more compact microcontroller(e.g. STM32) and thus programming it in `C` would significantly reduce the cost.

As for the complexity, it requires an understanding of microcontrollers, programming language, stepper motor controlling, mechanical structure, image processing, and possibly even project management. For a **single** freshman student, this could be quite challenging. Fortunately Rubik's cube solving algorithm(e.g. two phase) which is very complex, is open-source and thus we do not need to implement it by hand. I think a **team** of 3~5 students may be more suitable. A team can distribute the workload and leverage each member's strengths in different areas.

Hope my answer helps :)

**Comment by DragonFaty** [comment]
Thank you very much! Hope you have a nice day in HUST!
